/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DreamsNewRouteImport } from './routes/dreams/new'
import { Route as DreamsDreamIdRouteImport } from './routes/dreams/$dreamId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDreamsDreamIdImageRouteImport } from './routes/api/dreams/$dreamId/image'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamsNewRoute = DreamsNewRouteImport.update({
  id: '/dreams/new',
  path: '/dreams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamsDreamIdRoute = DreamsDreamIdRouteImport.update({
  id: '/dreams/$dreamId',
  path: '/dreams/$dreamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDreamsDreamIdImageRoute = ApiDreamsDreamIdImageRouteImport.update({
  id: '/api/dreams/$dreamId/image',
  path: '/api/dreams/$dreamId/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/health': typeof ApiHealthRoute
  '/dreams/$dreamId': typeof DreamsDreamIdRoute
  '/dreams/new': typeof DreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/health': typeof ApiHealthRoute
  '/dreams/$dreamId': typeof DreamsDreamIdRoute
  '/dreams/new': typeof DreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/health': typeof ApiHealthRoute
  '/dreams/$dreamId': typeof DreamsDreamIdRoute
  '/dreams/new': typeof DreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/api/health'
    | '/dreams/$dreamId'
    | '/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/health'
    | '/dreams/$dreamId'
    | '/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/api/health'
    | '/dreams/$dreamId'
    | '/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DreamsDreamIdRoute: typeof DreamsDreamIdRoute
  DreamsNewRoute: typeof DreamsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDreamsDreamIdImageRoute: typeof ApiDreamsDreamIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreams/new': {
      id: '/dreams/new'
      path: '/dreams/new'
      fullPath: '/dreams/new'
      preLoaderRoute: typeof DreamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreams/$dreamId': {
      id: '/dreams/$dreamId'
      path: '/dreams/$dreamId'
      fullPath: '/dreams/$dreamId'
      preLoaderRoute: typeof DreamsDreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dreams/$dreamId/image': {
      id: '/api/dreams/$dreamId/image'
      path: '/api/dreams/$dreamId/image'
      fullPath: '/api/dreams/$dreamId/image'
      preLoaderRoute: typeof ApiDreamsDreamIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  ApiHealthRoute: ApiHealthRoute,
  DreamsDreamIdRoute: DreamsDreamIdRoute,
  DreamsNewRoute: DreamsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDreamsDreamIdImageRoute: ApiDreamsDreamIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
