/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDreamsNewRouteImport } from './routes/_app/dreams/new'
import { Route as AppDreamsDreamIdRouteImport } from './routes/_app/dreams/$dreamId'
import { Route as ApiDreamsDreamIdImageRouteImport } from './routes/api/dreams/$dreamId/image'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDreamsNewRoute = AppDreamsNewRouteImport.update({
  id: '/dreams/new',
  path: '/dreams/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDreamsDreamIdRoute = AppDreamsDreamIdRouteImport.update({
  id: '/dreams/$dreamId',
  path: '/dreams/$dreamId',
  getParentRoute: () => AppRoute,
} as any)
const ApiDreamsDreamIdImageRoute = ApiDreamsDreamIdImageRouteImport.update({
  id: '/api/dreams/$dreamId/image',
  path: '/api/dreams/$dreamId/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof AppHomeRoute
  '/api/health': typeof ApiHealthRoute
  '/dreams/$dreamId': typeof AppDreamsDreamIdRoute
  '/dreams/new': typeof AppDreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof AppHomeRoute
  '/api/health': typeof ApiHealthRoute
  '/dreams/$dreamId': typeof AppDreamsDreamIdRoute
  '/dreams/new': typeof AppDreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/home': typeof AppHomeRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/dreams/$dreamId': typeof AppDreamsDreamIdRoute
  '/_app/dreams/new': typeof AppDreamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dreams/$dreamId/image': typeof ApiDreamsDreamIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/home'
    | '/api/health'
    | '/dreams/$dreamId'
    | '/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/home'
    | '/api/health'
    | '/dreams/$dreamId'
    | '/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sign-in'
    | '/_app/home'
    | '/api/health'
    | '/_app/dreams/$dreamId'
    | '/_app/dreams/new'
    | '/api/auth/$'
    | '/api/dreams/$dreamId/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDreamsDreamIdImageRoute: typeof ApiDreamsDreamIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dreams/new': {
      id: '/_app/dreams/new'
      path: '/dreams/new'
      fullPath: '/dreams/new'
      preLoaderRoute: typeof AppDreamsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dreams/$dreamId': {
      id: '/_app/dreams/$dreamId'
      path: '/dreams/$dreamId'
      fullPath: '/dreams/$dreamId'
      preLoaderRoute: typeof AppDreamsDreamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/dreams/$dreamId/image': {
      id: '/api/dreams/$dreamId/image'
      path: '/api/dreams/$dreamId/image'
      fullPath: '/api/dreams/$dreamId/image'
      preLoaderRoute: typeof ApiDreamsDreamIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppDreamsDreamIdRoute: typeof AppDreamsDreamIdRoute
  AppDreamsNewRoute: typeof AppDreamsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppDreamsDreamIdRoute: AppDreamsDreamIdRoute,
  AppDreamsNewRoute: AppDreamsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDreamsDreamIdImageRoute: ApiDreamsDreamIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
